-- schema.sql
CONNECT 'jdbc:derby://localhost:1527/tpchdb;create=true;user=app;password=app';

CREATE TABLE PART (
  P_PARTKEY INT PRIMARY KEY,
  P_NAME VARCHAR(55),
  P_MFGR CHAR(25),
  P_BRAND CHAR(10),
  P_TYPE VARCHAR(25),
  P_SIZE INT,
  P_CONTAINER CHAR(10),
  P_RETAILPRICE DECIMAL(15,2),
  P_COMMENT VARCHAR(23)
);

CREATE TABLE PARTSUPP (
  PS_PARTKEY INT REFERENCES PART(P_PARTKEY),
  PS_SUPPKEY INT,
  PS_AVAILQTY INT,
  PS_SUPPLYCOST DECIMAL(15,2),
  PS_COMMENT VARCHAR(199),
  PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

CREATE TABLE CUSTOMER (
  C_CUSTKEY INT PRIMARY KEY,
  C_NAME VARCHAR(25),
  C_ADDRESS VARCHAR(40),
  C_NATIONKEY INT,
  C_PHONE CHAR(15),
  C_ACCTBAL DECIMAL(15,2),
  C_MKTSEGMENT CHAR(10),
  C_COMMENT VARCHAR(117)
);

CREATE TABLE ORDERS (
  O_ORDERKEY INT PRIMARY KEY,
  O_CUSTKEY INT REFERENCES CUSTOMER(C_CUSTKEY),
  O_ORDERSTATUS CHAR(1),
  O_TOTALPRICE DECIMAL(15,2),
  O_ORDERDATE DATE,
  O_ORDERPRIORITY CHAR(15),
  O_CLERK CHAR(15),
  O_SHIPPRIORITY INT,
  O_COMMENT VARCHAR(79)
);
